RedHat 8 Compatibility
swisstxt/ansible-role-ntp pull request #1
Opened 2022-07-26 10:50 UTC by joschi36

Ensures Compatibility with RedHat 8 (Tested with AlmaLinux 8)

Ntpd not supported anymore. Now using chrony.

2022-07-26 12:17 UTC, josvo requested changes
Small comments, besides that, LGTM

2022-07-26 14:14 UTC, joschi36 commented on meta/main.yml
> +      - "8"
did not test yet :/

2022-07-26 14:15 UTC, joschi36 commented on meta/main.yml
> +      - "18"
will delete it

2022-07-27 06:46 UTC, josvo approved these changes
:+1:

2022-07-27 17:32 UTC, merged